### ISSUE TITLE
建议将游戏超时改成操作超时

### ISSUE THREAD

**Issue by lgc2333** [MeetWq/nonebot-plugin-minesweeper#2]
血压上来了
![Screenshot_20220418-235854](https://user-images.githubusercontent.com/59048777/163836859-5420e988-1687-4edc-b313-cbe6a672e8b5.png)

**Comment by MeetWq** [comment]
其实是因为时间最多只能显示999秒所以定的超时233

**Comment by MeetWq** [comment]
我之后改一下吧，不管时间了

**Comment by MeetWq** [comment]
现在改成 5 分钟无操作结束游戏了

显示的时间有可能会溢出（
